# Generated by Django 3.1.4 on 2020-12-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_auto_20201204_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='date_added',
        ),
    ]
